### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by MD-AZMAL** [MD-AZMAL/MD-AZMAL.github.io#3]
Make a more informative README for the website

**Comment by Yash-Handa** [comment]
On it

**Comment by Yash-Handa** [comment]
Hi, @MD-AZMAL 
Can you briefly provide topics to include in README.md : )

**Comment by MD-AZMAL** [comment]
Cool!
* Try to include a gif preview of the website.
* Resources used in making the website like bootstrap, fontawesome etc.
* Add a link to deployed url
